version: '3.8'

services:
  # Database
  mongodb:
    image: mongo:5.0
    container_name: ezbuy_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ParipaLaKaThum@!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ezbuy_network

  # User Service
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: ezbuy_user_service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:ParipaLaKaThum@!@mongodb:27017/ezbuy?authSource=admin
      - JWT_SECRET=your-secret-key-here
    depends_on:
      - mongodb
    networks:
      - ezbuy_network

  # Product Service
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: ezbuy_product_service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://admin:ParipaLaKaThum@!@mongodb:27017/ezbuy?authSource=admin
    depends_on:
      - mongodb
    networks:
      - ezbuy_network

  # Order Service
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: ezbuy_order_service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URI=mongodb://admin:ParipaLaKaThum@!@mongodb:27017/ezbuy?authSource=admin
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
    depends_on:
      - mongodb
      - user-service
      - product-service
    networks:
      - ezbuy_network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ezbuy_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - ezbuy_network

 # Nginx with Let's Encrypt support
  nginx:
    image: nginx:alpine
    container_name: ezbuy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-with-ssl.conf:/etc/nginx/nginx.conf
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - user-service
      - product-service
      - order-service
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - ezbuy_network

  # Certbot for Let's Encrypt
  certbot:
    image: certbot/certbot
    container_name: ezbuy_certbot
    restart: unless-stopped
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
      - ./ssl/certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mongodb_data:

networks:
  ezbuy_network:
    driver: bridge
